### ISSUE TITLE
Changes to -meta.xml only cause delta build to fail

### ISSUE THREAD

**Issue by rjfay** [amguerrero/sfdc_ant_tasks#13]
If a file's metadata (`-meta.xml`) is in the diff and not the file itself, only the `-meta.xml` file is added to the delta and the build fails.  I believe the code needs to check for this situation and pull in the non-meta file to ensure that the `-meta.xml` is updated.

**Comment by amguerrero** [comment]
Hi @rjfay!

Thanks for letting me know about this issue, I never thought of that scenario.

I'll fix it as soon as possible.

**Comment by rjfay** [comment]
Thanks @amguerrero!  I have created a fix that worked for us and will create a PR for it soon.  This is my first time working with Groovy, so I'm sure you could rewrite it to work better!

**Comment by rjfay** [comment]
Fixed by #16

**Comment by amguerrero** [comment]
@rjfay I'm not very good at groovy either :) all the ant tasks could be written much better, but I liked that at least you followed the current style
