### ISSUE TITLE
DeltaDeployment task API version

### ISSUE THREAD

**Issue by florianhoehn** [amguerrero/sfdc_ant_tasks#8]
Hey @amguerrero 

The delta deployment is working really well however there are two minor issues that I ran into and had to correct manually:

- the API version inside the package.xml is always 37 even when the main package.xml version is higher or lower. I would expect the API version to be copied over from the main package.xml.
- maybe because of this or because of you using the older version when developing it there are metadata items that do not get copied over into the package.xml that gets created. The one I found was "flowDefinition" which is a fairly new one.

Thanks! Appreciate your hard work on this :)

**Comment by amguerrero** [comment]
Hey @florianhoehn, 

I have just pushed a change that allows you to define the package version as an attribute for the delta deployment ant task, the attribute is **packageVersion**.
You can configure it in the build.xml file like this:
```
<!-- define the delta deployment task -->
<taskdef name="deltaDeployment"
    classpath="libs/SalesforceAntTasks-with-dependencies.jar"
    classname="sfanttasks.sfdeltadeployment.SFDeltaDeploymentTask" />

<!-- Use deltaDeployment task defining the package -->
<target name="get-delta-package">
    <deltaDeployment deltaFolder="delta"
        packageVersion="39.0"
        previousDeployment="v.1.0.1" />
</target>
```

Besides that I added to the default delta deployment task configuration the FlowDefinition metadata type, so with no extra configuration FlowDefinitions are now included in the delta package.

It was possible to change the package version and add the FlowDefinition via configuration, but I understand it's a bit cumbersome :)
You can create a config JSON file for delta deployment following the [/config/packageConfig.json](https://github.com/amguerrero/sfdc_ant_tasks/blob/master/config/packageConfig.json) (i.e. you can create it with the same name config/packageConfig.json and then use it when you call deltaDeployment like this:
```
<target name="get-delta-package">
    <deltaDeployment deltaFolder="delta"
        configFile="config/packageConfig.json"
        previousDeployment="v.1.0.1" />
</target>
```
If you use configFile with a version defined and you also define a version when as an attribute in the delta deployment ant task, it will use the package version in the attribute, it has priority over the one in the config file.

I hope it helps :)

**Comment by florianhoehn** [comment]
Brilliant! Thanks @amguerrero !
